@base_url = https://localhost:7114/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Vinicius",
    "cpf" : "231343423"
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST {{base_url}}/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 1000,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 2
}

### Obtenção de todas as folhas
GET {{base_url}}/funcionario/listar

### Obtenção de uma folha
GET {{base_url}}/folha/buscar/12345678912/10/2023

###

DELETE {{base_url}}/funcionario/deletar/6


###
PUT {{base_url}}/funcionario/alterar/3
Content-Type: application/json

{
    "nome": "TESTE",
    "cpf" : "2331231"
   
}